### ISSUE TITLE
secret @ c2c6e5e don't exist

### ISSUE THREAD

**Issue by Heniooo** [osuripple/old-frontend#1]
:/
![image](https://user-images.githubusercontent.com/14915249/37721529-0f9a3ff8-2d2a-11e8-861b-ef149c375418.png)

**Comment by kvzs** [comment]
its called secret for a reason, because it's secret.

**Comment by Heniooo** [comment]
but the files need it

**Comment by thehowl** [comment]
then you'll just have to remove the parts that require it
